# Generated by Django 5.0.3 on 2024-05-01 18:15

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=30)),
                ('Telefono', models.IntegerField()),
                ('Direccion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('dni', models.CharField(max_length=20)),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=30)),
                ('Descripcion', models.CharField(max_length=300)),
                ('Fecha_Inicio', models.DateField()),
                ('Fecha_Fin', models.DateField()),
                ('Presupuesto', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=30)),
                ('Descripcion', models.CharField(max_length=300)),
                ('Fecha_Inicio', models.DateField()),
                ('Fecha_Fin', models.DateField()),
                ('Nivel_Prioridad', models.IntegerField(validators=[django.core.validators.MaxValueValidator(3)])),
                ('Estado_Tarea', models.CharField(max_length=10)),
                ('Notas', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Encarga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Num_Proyectos', models.IntegerField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DjangoGePrApp.cliente')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DjangoGePrApp.proyecto')),
            ],
        ),
        migrations.CreateModel(
            name='Participa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DjangoGePrApp.cliente')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DjangoGePrApp.empleado')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DjangoGePrApp.proyecto')),
                ('tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DjangoGePrApp.tarea')),
            ],
        ),
    ]
