# Generated by Django 5.0.3 on 2024-05-25 11:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoGePrApp', '0003_alter_tarea_nivel_prioridad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='nivel_prioridad',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)]),
        ),
    ]
